import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import MAPS from '../data/maps'
import STRATS from '../data/strats'
import { track } from '../utils/analytics'
import './R6TierListPage.css'

// R6 ranked-pool operator tier list — generated by aggregating the
// strats data: for every (map, site, side), count how many sites each
// operator is listed as "essential", "recommended", or "flex". The
// resulting weighted score becomes the tier ranking.
//
// THIS PAGE IS DELIBERATELY DESIGNED AS LINK-BAIT.
//   - Public, no signup, no gate. Anyone can screenshot or quote it.
//   - Numbers are derived from data Aaron's curated personally, so when
//     other R6 sites cite it ("according to Recon 6's operator tier
//     list...") they're citing original work, not regurgitated meta.
//   - Schema-marked-up as ItemList so Google ranks it for "best R6
//     operators" / "R6 operator tier list" queries.
//   - Updated automatically every time the strats data is touched —
//     nothing to maintain manually.

const PRIORITY_WEIGHT = { essential: 3, recommended: 2, flex: 1 }
const RANKED_MAP_IDS = new Set(
  MAPS.filter((m) => m.rankedPool && !m.comingSoon && STRATS[m.id]).map((m) => m.id)
)

function buildTierList() {
  const index = {}
  for (const mapId of Object.keys(STRATS)) {
    if (!RANKED_MAP_IDS.has(mapId)) continue
    for (const siteId of Object.keys(STRATS[mapId])) {
      for (const side of ['attack', 'defense']) {
        const strat = STRATS[mapId][siteId]?.[side]
        if (!strat?.operators) continue
        for (const op of strat.operators) {
          const key = `${op.name}:${side}`
          if (!index[key]) {
            index[key] = {
              name: op.name,
              side,
              role: op.role,
              score: 0,
              essential: 0,
              recommended: 0,
              flex: 0,
              siteCount: 0,
              maps: new Set(),
            }
          }
          const entry = index[key]
          entry.score += PRIORITY_WEIGHT[op.priority] || 0
          entry[op.priority] = (entry[op.priority] || 0) + 1
          entry.siteCount += 1
          entry.maps.add(mapId)
          // Prefer the most-specific role label (longest string usually)
          if (!entry.role || op.role.length > entry.role.length) entry.role = op.role
        }
      }
    }
  }
  const all = Object.values(index)
  // Tier thresholds — top 10% = S, next 20% = A, next 30% = B, rest = C/D
  const scores = all.map((e) => e.score).sort((a, b) => b - a)
  const tierBreaks = {
    S: scores[Math.floor(scores.length * 0.10)] || 0,
    A: scores[Math.floor(scores.length * 0.30)] || 0,
    B: scores[Math.floor(scores.length * 0.60)] || 0,
  }
  for (const e of all) {
    e.mapCount = e.maps.size
    delete e.maps
    if (e.score >= tierBreaks.S) e.tier = 'S'
    else if (e.score >= tierBreaks.A) e.tier = 'A'
    else if (e.score >= tierBreaks.B) e.tier = 'B'
    else e.tier = 'C'
  }
  all.sort((a, b) => b.score - a.score || b.essential - a.essential)
  return all
}

const TIER_LIST = buildTierList()
const ATTACK_OPS = TIER_LIST.filter((e) => e.side === 'attack')
const DEFENSE_OPS = TIER_LIST.filter((e) => e.side === 'defense')

const TIER_ORDER = ['S', 'A', 'B', 'C']
const TIER_LABEL = {
  S: 'S-tier · Must pick',
  A: 'A-tier · Strong pick',
  B: 'B-tier · Situational',
  C: 'C-tier · Niche / flex',
}
const TIER_COLOR = {
  S: '#ff8a8a',
  A: '#ffc97a',
  B: '#00e5ff',
  C: 'rgba(230,233,239,0.6)',
}

function groupByTier(list) {
  const out = { S: [], A: [], B: [], C: [] }
  for (const op of list) out[op.tier].push(op)
  return out
}

export default function R6TierListPage() {
  const [side, setSide] = useState('attack')
  const grouped = useMemo(() => groupByTier(side === 'attack' ? ATTACK_OPS : DEFENSE_OPS), [side])
  const totalOps = (side === 'attack' ? ATTACK_OPS : DEFENSE_OPS).length

  // ItemList JSON-LD — feeds Google rich-results for "best operators"
  // style queries, since each tier is a ranked list of items.
  const itemListLd = useMemo(() => ({
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: `R6 Siege ${side === 'attack' ? 'Attack' : 'Defense'} Operator Tier List — Recon 6`,
    itemListOrder: 'https://schema.org/ItemListOrderDescending',
    numberOfItems: totalOps,
    itemListElement: (side === 'attack' ? ATTACK_OPS : DEFENSE_OPS).slice(0, 20).map((op, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: op.name,
      description: `${op.tier}-tier ${op.role} — ${op.essential} essential / ${op.recommended} recommended picks across ${op.mapCount} ranked maps`,
    })),
  }), [side, totalOps])

  return (
    <div className="r6-tier-page">
      <header className="r6-tier-header">
        <div className="r6-tier-eyebrow">R6 Siege · Ranked tier list · Updated automatically</div>
        <h1>R6 Operator <span className="r6-tier-accent">Tier List</span></h1>
        <p className="r6-tier-lead">
          Computed from {RANKED_MAP_IDS.size} ranked maps' worth of curated site-level picks.
          Each operator is scored by how often they're tagged <strong>essential</strong> (3 points),
          <strong> recommended</strong> (2 points), or <strong>flex</strong> (1 point) across attack
          or defense sites. Updated automatically when the strats data changes — no stale meta lists here.
        </p>
        <p className="r6-tier-cite-line">
          <strong>Citing this list?</strong> Use: <em>"Recon 6 R6 Operator Tier List, r6coaching.com/#/tools/r6-tier-list"</em>
        </p>
      </header>

      <div className="r6-tier-side-toggle">
        <button
          type="button"
          className={`r6-tier-side-btn attack${side === 'attack' ? ' active' : ''}`}
          onClick={() => { setSide('attack'); track('R6 Tier List Side', { side: 'attack' }) }}
        >
          Attack ({ATTACK_OPS.length})
        </button>
        <button
          type="button"
          className={`r6-tier-side-btn defense${side === 'defense' ? ' active' : ''}`}
          onClick={() => { setSide('defense'); track('R6 Tier List Side', { side: 'defense' }) }}
        >
          Defense ({DEFENSE_OPS.length})
        </button>
      </div>

      {TIER_ORDER.map((tier) => (
        <section key={tier} className={`r6-tier-row tier-${tier}`}>
          <header className="r6-tier-row-head" style={{ borderColor: TIER_COLOR[tier] }}>
            <div className="r6-tier-badge" style={{ background: TIER_COLOR[tier], color: '#0a0f19' }}>{tier}</div>
            <div className="r6-tier-row-title">{TIER_LABEL[tier]}</div>
            <div className="r6-tier-row-count">{grouped[tier].length} ops</div>
          </header>
          {grouped[tier].length === 0 ? (
            <div className="r6-tier-empty">No operators in this tier for {side === 'attack' ? 'attack' : 'defense'}.</div>
          ) : (
            <div className="r6-tier-grid">
              {grouped[tier].map((op) => (
                <div key={op.name} className="r6-tier-op-card" style={{ borderLeftColor: TIER_COLOR[tier] }}>
                  <div className="r6-tier-op-head">
                    <Link
                      to={`/operators/${encodeURIComponent(op.name.toLowerCase())}`}
                      className="r6-tier-op-name"
                    >
                      {op.name}
                    </Link>
                    <span className="r6-tier-op-score">{op.score} pts</span>
                  </div>
                  <div className="r6-tier-op-role">{op.role}</div>
                  <div className="r6-tier-op-stats">
                    {op.essential > 0 && (
                      <span className="r6-tier-stat ess">{op.essential} essential</span>
                    )}
                    {op.recommended > 0 && (
                      <span className="r6-tier-stat rec">{op.recommended} rec</span>
                    )}
                    {op.flex > 0 && (
                      <span className="r6-tier-stat flex">{op.flex} flex</span>
                    )}
                    <span className="r6-tier-stat maps">{op.mapCount} {op.mapCount === 1 ? 'map' : 'maps'}</span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>
      ))}

      <section className="r6-tier-methodology">
        <h2>Methodology</h2>
        <p>
          This list isn't pulled from anyone's gut — it's a direct aggregation of Recon 6's per-site
          operator recommendations across every ranked-pool R6 map currently in the data file.
        </p>
        <ul>
          <li><strong>Essential (3 pts):</strong> the operator is core to that site's standard plan. Without them, the plan breaks.</li>
          <li><strong>Recommended (2 pts):</strong> strong supporting pick that elevates the plan.</li>
          <li><strong>Flex (1 pt):</strong> situational pick that works on this site under specific reads.</li>
        </ul>
        <p>
          Total score = essential×3 + recommended×2 + flex×1, summed across all sites where the op
          appears for the active side (attack or defense). Tier thresholds: top 10% = S, next 20% = A,
          next 30% = B, rest = C.
        </p>
        <p>
          <strong>What this list won't tell you:</strong> ban rate (depends on who you're playing),
          fragging ceiling (a player skill), or pro-play viability (different rulesets). It tells you
          the breadth of an operator's competitive utility across the ranked map pool — which is exactly
          what matters when you're deciding who to learn first.
        </p>
      </section>

      <footer className="r6-tier-foot">
        <p>
          Want to actually use this intel in a match? <Link to="/live">Open Live Coach</Link> — picks your
          operator based on map, bans, side, and queue size, all in 90 seconds.
        </p>
      </footer>

      <script
        type="application/ld+json"
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: JSON.stringify(itemListLd) }}
      />
    </div>
  )
}
