// The operator posts and the VOD reviewer's r6-context.json are generated by
// hand, not by the build, which is how they drifted behind maps.js. These
// checks fail when either falls out of step again, and keep room names nobody
// has seen in game out of the reviewer's context.
import assert from 'node:assert/strict'
import { readFileSync, readdirSync } from 'node:fs'
import test from 'node:test'

import MAPS from '../src/data/maps.js'
import { verifiedFor } from '../src/data/verified-callouts.js'

const root = new URL('../', import.meta.url)
const context = JSON.parse(readFileSync(new URL('lambda/vod/r6-context.json', root), 'utf8'))
const words = (s) => ` ${String(s).toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()} `
const unescape = (s) => s.replace(/&quot;/g, '"').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&')

test('r6-context.json has every map and site in maps.js, with current names', () => {
  assert.deepEqual(Object.keys(context.maps).sort(), MAPS.map((m) => m.id).sort())
  for (const map of MAPS) {
    assert.deepEqual(
      context.maps[map.id].sites.map(({ id, name, floor }) => ({ id, name, floor })),
      map.sites.map(({ id, name, floor }) => ({ id, name, floor })),
      map.id,
    )
  }
})

test('r6-context.json callouts were all read off match footage', () => {
  for (const [mapId, map] of Object.entries(context.maps)) {
    const seen = verifiedFor(mapId)
    const names = seen ? [...seen.sites, ...seen.spawns, ...seen.callouts].map((e) => words(e.name)) : []
    for (const site of map.sites) {
      for (const callout of site.callouts) {
        assert.ok(names.some((n) => n.includes(words(callout))), `${mapId}/${site.id}: "${callout}" was never seen in footage`)
      }
    }
  }
})

test('operator posts list only sites in maps.js and no placeholder copy', () => {
  const blog = new URL('public/blog/', root)
  const posts = readdirSync(blog).filter((f) => /^r6-operator-.+\.html$/.test(f))
  assert.ok(posts.length > 0)
  const row = /<a href="\/guides\/([^"]+)\.html">[^<]*<\/a><\/td>\s*<td>([^<]*) <span[^>]*>\(([^)]*)\)<\/span><\/td>/g
  for (const file of posts) {
    const html = readFileSync(new URL(file, blog), 'utf8')
    assert.doesNotMatch(html, /VERIFY:|Unique gadget/, `${file} has placeholder copy`)
    let rows = 0
    for (const [, mapId, siteName, floor] of html.matchAll(row)) {
      rows++
      const map = MAPS.find((m) => m.id === mapId)
      assert.ok(map, `${file}: unknown map ${mapId}`)
      const site = map.sites.find((s) => s.name === unescape(siteName))
      assert.ok(site, `${file}: "${unescape(siteName)}" is not a ${map.name} site in maps.js`)
      assert.equal(floor, site.floor || '—', `${file}: ${site.name} floor`)
    }
    assert.ok(rows > 0, `${file}: no site rows found`)
  }
})
