// Help Center articles (ARCHITECTURE §13).
//
// Reviewed 2026-09-28 against the production release line: every statement
// below was checked claim by claim against the code in this repository (the
// file:line evidence is in docs/player-success/HELP-REVIEW-2026-09-28.md) and
// each article cites the files it rests on in `sources`. Statements that are
// business or legal policy rather than product behaviour are left out and
// listed in that review as held for a decision (billing-portal capabilities,
// data export/deletion handling, AI-review retention, how Champions redeem
// included sessions). Public search serves `status: 'reviewed'` articles only.
//
// Copy rules: no trial wording, no coaching prices, no claim that any
// coaching session costs nothing, no pricing numbers (current prices live on
// the pricing page), no quoted paid strat text, no real names or gamertags,
// no time or refund promises.

const REVIEWED = Object.freeze({ status: 'reviewed', reviewedBy: 'Release review 2026-09-28 (checked against production code)', reviewedOn: '2026-09-28' })

export const ARTICLES = Object.freeze([
  {
    slug: 'connect-your-gaming-account',
    title: 'Connect your gaming account',
    category: 'ubisoft_connection',
    intents: ['how_to', 'broken'],
    summary: 'Tell Recon which platform and in-game name you play on so plans, your rank and your tracker link fit your account.',
    keywords: ['ubisoft', 'ubi connect', 'psn', 'playstation', 'xbox', 'gamertag', 'platform', 'link', 'connect', 'tracker', 'in-game name'],
    body: [
      '## What Recon asks for',
      'When you set up your player profile, Recon asks for a display name and your platform (PC, Xbox or PlayStation). Everything else is optional: region, Discord, current rank, goal rank, main role and Ubisoft username. You can skip setup and finish it later.',
      '## Where to change it',
      '- Account page: "In-game name (Ubisoft / Xbox / PSN ID)" and your platform.',
      '- Your Recon home: rank and goal.',
      '- Progress page: upload a screenshot of your Ubisoft or TRN overview. Recon reads the visible rank and stats and asks you to confirm them.',
      '## What "connected" means',
      'Recon uses the name and platform on your Account page to link to your public tracker profile and to tie a confirmed rank screenshot to that account. It does not pull stats automatically, and it does not verify that you own the account, so type the name exactly as it appears in game.',
      '## Your passwords stay yours',
      'Recon never asks for your Ubisoft, PlayStation or Xbox password. Recon\'s player-data service rejects any password or token field sent to it. If someone asks for your password in Recon\'s name, report it from Support. If you can\'t sign in, email support@r6coaching.com.',
    ].join('\n'),
    ...REVIEWED,
    sources: ['src/components/ProfileSetupModal.jsx', 'src/pages/AccountPage.jsx', 'src/pages/ProgressPage.jsx', 'src/lib/r6Identity.js', 'src/features/home/RankGoalEditor.jsx', 'lambda/player-data/core.mjs', 'lambda/player-data/providers.mjs'],
  },
  {
    slug: 'upload-a-vod-for-ai-review',
    title: 'Upload a VOD for AI review',
    category: 'vod_upload',
    intents: ['how_to', 'broken'],
    summary: 'AI VOD review works from screenshots of one round. Here is what it accepts, how the allowance works and what counts against it.',
    keywords: ['vod', 'upload', 'screenshots', 'images', 'png', 'jpg', 'webp', 'review', 'analysis', 'allowance', 'limit', 'video', 'clip', 'large', 'too large'],
    body: [
      '## What to upload',
      'VOD review reads screenshots, not video files. Upload screenshots from one round: PNG, JPG, WEBP or GIF, up to 5 MB each. The upload box shows how many screenshots your plan allows per review: Pro up to 5, Elite and Champion up to 10.',
      'Video clips and stream links are not supported. AI VOD review is included with Pro and above.',
      '## Add context (optional)',
      'After you add your screenshots, open "Add context hints (optional)" to pick the map, site, side and operator. The review uses the map and site you pick, which makes the feedback sharper.',
      '## Your allowance',
      'Paid plans include a set number of reviews per 30-day period. The period starts with your first review after the previous one ended. Your usage shows above the upload box and on your Account page; after your first review in a period, both show when it resets. When the allowance is used up, the page tells you and shows the reset date.',
      '## What counts',
      'A review that fails after the AI has started still counts toward your allowance. Problems caught before that do not count: a wrong file type, a file that is too large, or too many screenshots.',
      '## Keep what you need',
      'Your account keeps a short summary of each review: the main mistake, a drill and the score. You can\'t reopen the full report later, so save anything you want to keep.',
      '## If something goes wrong',
      'If the page says the images could not be analysed, try clearer PNG or JPG screenshots. If it says reviews are rate-limited, paused or could not be reserved, try again later. If you think a review was counted by mistake, open a case from Support with roughly when it happened.',
    ].join('\n'),
    ...REVIEWED,
    sources: ['src/pages/VodPage.jsx', 'src/components/vod/SessionUploadZone.jsx', 'lambda/vod/index.mjs', 'lambda/vod/coach-contract.mjs', 'src/api/vodApi.js', 'src/pages/AccountPage.jsx'],
  },
  {
    slug: 'match-replays',
    title: 'Can I upload match replays?',
    category: 'replay_upload',
    intents: ['how_to'],
    summary: 'Replay (.rec) upload is not available in Recon. Screenshot-based VOD review is.',
    keywords: ['replay', 'rec', '.rec', 'match replay', 'replay file', 'upload replay'],
    body: [
      '## Short answer',
      'Recon does not accept replay (.rec) files, and nothing on the website reads replays from your game.',
      '## What works now',
      'For an AI review of a round (Pro and above), take screenshots of the key moments and upload them on the VOD review page. See "Upload a VOD for AI review".',
      '## Want replay support?',
      'Tell us in Support what you would use it for. We log it as a replay request.',
    ].join('\n'),
    ...REVIEWED,
    sources: ['lambda/player-data/providers.mjs', 'lambda/customer-success/support/diagnostics/replay.mjs', 'src/pages/VodPage.jsx', 'lambda/vod/index.mjs'],
  },
  {
    slug: 'why-rank-or-stats-look-different',
    title: 'Why your rank or stats look different in Recon',
    category: 'rank_stat_discrepancy',
    intents: ['broken', 'how_to'],
    summary: 'Where each number comes from, how fresh it is, and what to do when it does not match the game.',
    keywords: ['rank', 'wrong rank', 'stats', 'kd', 'k/d', 'win rate', 'mmr', 'outdated', 'season', 'tracker', 'mismatch'],
    body: [
      '## Where the numbers come from',
      '- The rank on your Recon home is the last rank you saved: from profile setup, from your home, or a rank you confirmed from a screenshot on the Progress page. Update it from your home.',
      '- Recon does not pull stats from Tracker Network or read your rank live from Ubisoft. On the Progress page you can upload a screenshot of your Ubisoft or TRN overview; Recon reads the visible rank and stats and asks you to confirm them. After 24 hours it asks for a new screenshot.',
      '## Common reasons for a difference',
      '- A new season reset or re-placed your rank in game.',
      '- The rank you saved was set a while ago and not updated.',
      '- The in-game name or platform on your Account page doesn\'t match the account you play ranked on.',
      '## Still wrong?',
      'Open a case from Support with the rank or stat you see in game and where Recon shows something different. Recon keeps the latest rank you saved and, for a screenshot, when you confirmed it. Add a screenshot of your in-game rank to the case.',
    ].join('\n'),
    ...REVIEWED,
    sources: ['lambda/customer-success/domain/facts.mjs', 'src/features/home/RankGoalEditor.jsx', 'src/pages/ProgressPage.jsx', 'src/lib/r6Identity.js', 'lambda/trn/index.mjs', 'lambda/player-data/providers.mjs'],
  },
  {
    slug: 'how-recon-history-works',
    title: 'How Recon keeps your history',
    category: 'historical_data',
    intents: ['how_to'],
    summary: 'Recon\'s player record stores dated snapshots with their source, so progress has a timeline you can trust.',
    keywords: ['history', 'historical', 'tracking', 'snapshots', 'progress', 'timeline', 'export', 'delete', 'data', 'privacy'],
    body: [
      '## Dated snapshots',
      'Recon\'s player record stores dated snapshots with their source and how they were verified. New snapshots are added instead of overwriting older ones. Profile values such as your saved rank and goal are different: saving a new one replaces the old one.',
      '## Which value Recon shows',
      'Recon prefers a value from the last 24 hours, then the more trusted source (official data over your own input), then the most recent. Anything older than a day is treated as stale, and values you reported yourself stay labelled as self-reported.',
      '## Your data',
      'Your history isn\'t shared with other players. Recon staff can see it when helping you. For a copy of your data or to ask for it to be deleted, follow the Privacy page: email support@r6coaching.com from your account email with "Privacy request" in the subject.',
    ].join('\n'),
    ...REVIEWED,
    sources: ['docs/RECON-PLAYER-DATA-FOUNDATION.md', 'lambda/player-data/core.mjs', 'lambda/player-data/index.mjs', 'src/pages/PrivacyPage.jsx'],
  },
  {
    slug: 'subscription-and-access',
    title: 'Your plan and what it unlocks',
    category: 'subscription',
    intents: ['how_to', 'broken'],
    summary: 'What Basic, Pro, Elite and Champion include, where to see your plan, and why features can pause.',
    keywords: ['plan', 'subscription', 'membership', 'tier', 'pro', 'elite', 'champion', 'basic', 'access', 'locked', 'upgrade', 'features', 'include', 'includes'],
    body: [
      '## Plans',
      '- Basic (free account): the Bank and Coastline round plans, the operator catalog, match prep from public data and the Road to Champion checklist.',
      '- Pro: plans for every map and site, ban recommendations and enemy intel, AI VOD review and the Windows desktop app (beta).',
      '- Elite: everything in Pro, plus premium tactics and verified setups and a larger VOD review allowance.',
      '- Champion: everything in Elite, plus two live 1:1 coaching sessions a month. See "Coaching credits and booking sessions" before you book.',
      'Current prices are on the pricing page.',
      '## Where to see your plan',
      'Your Account page shows your plan and what you have access to. Your Recon home shows your membership status.',
      '## Why paid features can pause',
      'Paid features stay on while your membership is active. If a payment fails, paid features pause; they come back once a payment goes through. If you paid and a feature is still locked, open a case from Support: we can see your membership record, so you will not need to resend payment details.',
    ].join('\n'),
    ...REVIEWED,
    sources: ['lambda/customer-success/domain/plans.mjs', 'src/config/planFacts.js', 'src/components/strats/ChampionGate.jsx', 'lambda/subscription/index.mjs', 'lambda/webhook/index.mjs', 'src/pages/AccountPage.jsx', 'lambda/customer-success/domain/home.mjs'],
  },
  {
    slug: 'coaching-credits',
    title: 'Coaching credits and booking sessions',
    category: 'coaching_credits',
    intents: ['how_to', 'broken'],
    summary: 'How Champion coaching credits are added, why the booking page does not use them yet, and how to move a session.',
    keywords: ['coaching', 'credits', 'session', 'book', 'booking', '1:1', 'one on one', 'reschedule', 'coach'],
    body: [
      '## How credits are added',
      'A Champion membership sets your coaching credits to two each time the monthly payment goes through. Unused credits do not roll over to the next month.',
      '## Champion members: before you book',
      'The coaching page does not apply your included credits yet: it sends every booking to card checkout. Don\'t pay by card for a session your plan includes. Open a case from Support to use an included session.',
      '## Booking a paid session',
      'Book from the coaching page. It shows the session length and the times you can pick. A slot is held for a few minutes while you finish booking.',
      '## Changing a session',
      'To move a session, use the reschedule link in your confirmation email. Don\'t cancel and rebook: cancelling does not return a credit.',
      '## Credits look wrong?',
      'Open a case from Support with roughly when you paid. We can see your bookings and the credits on record.',
    ].join('\n'),
    ...REVIEWED,
    sources: ['lambda/booking/index.mjs', 'lambda/webhook/index.mjs', 'public/coaching/index.html', 'lambda/customer-success/domain/plans.mjs', 'lambda/customer-success/support/diagnostics/coaching.mjs'],
  },
  {
    slug: 'billing-and-payments',
    title: 'Billing, payments and cancelling',
    category: 'billing_question',
    intents: ['how_to', 'broken'],
    summary: 'Where to manage billing, what to do when a payment fails, and how to ask about a charge you do not recognise.',
    keywords: ['billing', 'payment', 'card', 'update my card', 'invoice', 'receipt', 'charged', 'charge', 'cancel', 'cancellation', 'refund', 'declined', 'past due', 'stripe'],
    body: [
      '## Managing billing',
      'While your membership is active, "Manage billing" on your Account page opens Stripe\'s secure billing portal, where your subscription and payment details are managed. Payments are handled by Stripe.',
      '## If a payment fails',
      'Paid features pause until a payment goes through. Use "Update payment method" on your Recon home to change your card. If you cannot find the way in, open a case from Support.',
      '## A charge you do not recognise',
      'Open a case from Support with the date and amount on your statement. We can see your membership record and will check it against the charge. Billing corrections are reviewed and made by a person.',
    ].join('\n'),
    ...REVIEWED,
    sources: ['lambda/subscription/index.mjs', 'src/pages/AccountPage.jsx', 'lambda/customer-success/domain/mission.mjs', 'src/features/home/sections.jsx'],
  },
  {
    slug: 'get-better-vod-results',
    title: 'Get better results from AI VOD review',
    category: 'ai_result',
    intents: ['how_to', 'value'],
    summary: 'Small changes to what you upload make the review much sharper.',
    keywords: ['better results', 'better', 'feedback', 'vod tips', 'screenshots', 'context', 'map', 'site', 'operator', 'wrong map', 'generic', 'accuracy', 'improve'],
    body: [
      '## Pick the context',
      'After you add your screenshots, open "Add context hints (optional)" and pick the map, site, side and operator. The review then uses that site\'s callouts and setup notes and that operator\'s role instead of guessing from the image.',
      '## Choose the right screenshots',
      '- Use screenshots from one round, in order: prep, the fight, and what happened after.',
      '- Full-screen, clear PNG or JPG images read best. Avoid phone photos of a monitor.',
      '- Use Siege gameplay only. If none of the screenshots look like Siege, the review stops and says so, and that attempt still counts toward your allowance.',
      '## Read it as a plan',
      'The review is set up to say when it is unsure instead of guessing. Take the practice plan into your next session and review again after a few matches.',
    ].join('\n'),
    ...REVIEWED,
    sources: ['lambda/vod/index.mjs', 'lambda/vod/coach-contract.mjs', 'lambda/vod/r6-context.json', 'src/components/vod/SessionUploadZone.jsx'],
  },
  {
    slug: 'desktop-client',
    title: 'The desktop app',
    category: 'desktop_client',
    intents: ['how_to', 'broken'],
    summary: 'How paid members install and activate the Windows desktop app (beta), and what to send us if it is not working.',
    keywords: ['desktop', 'app', 'desktop app', 'overlay', 'install', 'installer', 'download', 'capture card', 'live coach', 'windows', 'activation', 'token'],
    body: [
      '## Availability',
      'Paid members can download the Windows desktop app (beta) from Desktop setup in the account menu, then activate it with the token on the Activation page. A token stops working after 30 days or at the end of your paid period, whichever comes first; get a fresh one from the Activation page.',
      'The installer is not code-signed yet, so Windows SmartScreen may warn you. Choose More info, then Run anyway.',
      '## If you have the app and it is not working',
      'Recon cannot see which version you installed or whether it activated. Open a case from Support with the app version, your Windows version, and whether you use PC capture or a console capture card.',
    ].join('\n'),
    ...REVIEWED,
    sources: ['src/main.jsx', 'src/components/Navbar.jsx', 'src/pages/DownloadPage.jsx', 'src/pages/ActivatePage.jsx', 'lambda/subscription/index.mjs'],
  },
  {
    slug: 'sign-in-and-password-help',
    title: 'Sign-in, confirmation code and password help',
    category: 'account_login',
    intents: ['how_to', 'broken'],
    summary: 'Fix the most common sign-in problems: missing confirmation code, forgotten password, email typed differently.',
    keywords: ['login', 'log in', 'sign in', 'password', 'forgot password', 'reset', 'confirmation code', 'verification', 'code', 'email', 'locked out'],
    body: [
      '## Confirmation code',
      'After sign-up, Recon emails a confirmation code. If it is not in your inbox, check spam and promotions. If you try to sign in before confirming, the sign-in page takes you back to the confirm step.',
      '## Forgot your password',
      'Choose "Forgot password?" on the sign-in page. Recon emails a 6-digit code, and you enter it with your new password. Passwords need at least 12 characters.',
      '## Email typed differently',
      'Recon tries your email in lowercase first, then exactly as you typed it. If your account was created with capital letters in the email, type it exactly as you signed up. If you still can\'t sign in, email support@r6coaching.com from the address you signed up with.',
    ].join('\n'),
    ...REVIEWED,
    sources: ['src/pages/AuthPage.jsx', 'src/hooks/useAuth.jsx', 'src/features/support/player/SupportPage.jsx'],
  },
])

export function articleBySlug(slug) {
  return ARTICLES.find((a) => a.slug === slug) || null
}
