// Help Center articles (ARCHITECTURE §13). DRAFTS ONLY.
//
// Every statement is based on product behaviour in this repository; each
// article cites the files it was checked against in `sources`. Every article
// is `status: 'draft'`, `reviewedBy: null` until Aaron reviews it, and the
// public search serves reviewed articles only.
//
// Copy rules: no trial wording, no coaching prices, no claim that any
// coaching session costs nothing, no pricing numbers (current prices live on
// the pricing page), no quoted paid strat text, no real names or gamertags,
// no time or refund promises.

export const ARTICLES = Object.freeze([
  {
    slug: 'connect-your-gaming-account',
    title: 'Connect your gaming account',
    category: 'ubisoft_connection',
    intents: ['how_to', 'broken'],
    summary: 'Tell Recon which platform and in-game name you play on so plans and stats fit your account.',
    keywords: ['ubisoft', 'ubi connect', 'psn', 'playstation', 'xbox', 'gamertag', 'platform', 'link', 'connect', 'tracker', 'in-game name'],
    body: [
      '## What Recon asks for',
      'When you finish your player profile, Recon asks for your platform (PC, Xbox or PlayStation). Your Ubisoft username, current rank, goal rank and main role are optional and can be added later.',
      '## Where to change it',
      '- Account page: the in-game name field (Ubisoft, Xbox or PSN ID).',
      '- Your Recon home: rank and goal.',
      '- Progress page: "Connect tracker" saves the name and platform the tracker should look up.',
      '## What "connected" means',
      'Recon uses the name you enter to look up public data. It does not verify that you own the account, so type it exactly as it appears in game.',
      '## Your passwords stay yours',
      'Recon never asks for your Ubisoft, PlayStation or Xbox password, and it refuses password or token fields if anything tries to send them. If someone asks for your password in Recon\'s name, report it from Get Help.',
    ].join('\n'),
    status: 'draft',
    reviewedBy: null,
    sources: ['src/components/ProfileSetupModal.jsx', 'src/pages/AccountPage.jsx', 'src/pages/ProgressPage.jsx', 'src/features/home/RankGoalEditor.jsx', 'lambda/player-data/core.mjs', 'lambda/player-data/providers.mjs'],
  },
  {
    slug: 'upload-a-vod-for-ai-review',
    title: 'Upload a VOD for AI review',
    category: 'vod_upload',
    intents: ['how_to', 'broken'],
    summary: 'AI VOD review works from screenshots of one round. Here is what it accepts and what the limits are.',
    keywords: ['vod', 'upload', 'screenshots', 'images', 'png', 'jpg', 'webp', 'review', 'analysis', 'allowance', 'limit', 'video', 'clip'],
    body: [
      '## What to upload',
      'VOD review reads screenshots, not video files. Upload screenshots from one round: PNG, JPG, WEBP or GIF, up to 5 MB each. The upload box shows how many screenshots your plan allows per review (Pro: up to 5; never more than 10).',
      'Video clips and stream links are not supported today.',
      '## Add context (optional)',
      'Open "Add context hints" to pick the map, site, side and operator. The review uses the map and site you pick, which makes the feedback sharper.',
      '## Your allowance',
      'Paid plans include a monthly number of reviews. Your usage shows above the upload box and on your Account page, with the date it resets. When the allowance is used up, the page tells you and shows the reset date.',
      '## Keep what you need',
      'Recon keeps your review count and a summary, not the full report. Save anything you want to keep.',
      '## If something goes wrong',
      'If the page says the images could not be analysed, try clearer PNG or JPG screenshots. If it says the service is busy, try again a little later. If a review fails and you think it counted against your allowance, open a Get Help case with roughly when it happened.',
    ].join('\n'),
    status: 'draft',
    reviewedBy: null,
    sources: ['src/pages/VodPage.jsx', 'src/components/vod/SessionUploadZone.jsx', 'lambda/vod/index.mjs', 'lambda/customer-success/domain/home.mjs', 'src/pages/AccountPage.jsx'],
  },
  {
    slug: 'match-replays',
    title: 'Can I upload match replays?',
    category: 'replay_upload',
    intents: ['how_to'],
    summary: 'Replay (.rec) upload is not available in Recon today. Screenshot-based VOD review is.',
    keywords: ['replay', 'rec', '.rec', 'match replay', 'replay file', 'upload replay'],
    body: [
      '## Short answer',
      'Recon does not accept replay (.rec) files today, and nothing reads replays from your game.',
      '## What works now',
      'For an AI review of a round, take screenshots of the key moments and upload them on the VOD review page. See "Upload a VOD for AI review".',
      '## Want replay support?',
      'Tell us on Get Help what you would use it for. Requests are logged as feature requests.',
    ].join('\n'),
    status: 'draft',
    reviewedBy: null,
    sources: ['lambda/player-data/providers.mjs', 'src/pages/VodPage.jsx', 'lambda/vod/index.mjs'],
  },
  {
    slug: 'why-rank-or-stats-look-different',
    title: 'Why your rank or stats look different in Recon',
    category: 'rank_stat_discrepancy',
    intents: ['broken', 'how_to'],
    summary: 'Where each number comes from, how fresh it is, and what to do when it does not match the game.',
    keywords: ['rank', 'wrong rank', 'stats', 'kd', 'k/d', 'win rate', 'mmr', 'outdated', 'season', 'tracker', 'mismatch'],
    body: [
      '## Where the numbers come from',
      '- The rank on your Recon home is the rank you entered in your profile. Update it there when you rank up or down.',
      '- Tracker stats on the Progress page come from Tracker Network when that lookup is available. Results are cached for a few minutes, so a match you just finished may not show yet.',
      '- Recon does not read your rank live from Ubisoft.',
      '## Common reasons for a difference',
      '- A new season reset or re-placed your rank in game.',
      '- The profile rank was set a while ago and not updated.',
      '- The tracker is looking up a different name or platform. Check the in-game name on your Account page.',
      '## Still wrong?',
      'Open a Get Help case with the rank or stat you see in game and where Recon shows something different. Recon keeps dated records of each value and where it came from, so we can check whether the gap is on the source side or ours.',
    ].join('\n'),
    status: 'draft',
    reviewedBy: null,
    sources: ['src/features/home/PlayerHome.jsx', 'src/features/home/RankGoalEditor.jsx', 'src/pages/ProgressPage.jsx', 'lambda/trn/index.mjs', 'lambda/player-data/core.mjs'],
  },
  {
    slug: 'how-recon-history-works',
    title: 'How Recon keeps your history',
    category: 'historical_data',
    intents: ['how_to'],
    summary: 'Recon stores dated snapshots with their source, so your progress has a timeline you can trust.',
    keywords: ['history', 'historical', 'tracking', 'snapshots', 'progress', 'timeline', 'export', 'delete', 'data', 'privacy'],
    body: [
      '## Dated snapshots',
      'Each time Recon records a value about you (for example a rank you entered, or a summary from a VOD review), it keeps it as a dated snapshot with its source and how it was verified. Older snapshots are kept, so history is not overwritten.',
      '## Which value Recon shows',
      'When several sources have the same value, Recon prefers the more authoritative, more recent one. Anything older than a day is treated as stale, and self-reported values stay labelled as self-reported.',
      '## Your data',
      'Your history is private to you by default. To get a copy of your data or to have it deleted, open a Get Help case. A person verifies the request from your account email before anything is exported or deleted.',
    ].join('\n'),
    status: 'draft',
    reviewedBy: null,
    sources: ['docs/RECON-PLAYER-DATA-FOUNDATION.md', 'lambda/player-data/core.mjs', 'lambda/player-data/index.mjs', 'docs/player-success/ARCHITECTURE.md'],
  },
  {
    slug: 'subscription-and-access',
    title: 'Your plan and what it unlocks',
    category: 'subscription',
    intents: ['how_to', 'broken'],
    summary: 'What Basic, Pro, Elite and Champion include, where to see your plan, and why features can pause.',
    keywords: ['plan', 'subscription', 'membership', 'tier', 'pro', 'elite', 'champion', 'basic', 'access', 'locked', 'upgrade', 'features'],
    body: [
      '## Plans',
      '- Basic (free account): sample maps and round plans, the operator catalog and the Road to Champion checklist.',
      '- Pro: every ranked map and site plan, match prep and ban recommendations, and AI VOD review.',
      '- Elite: everything in Pro, plus premium tactics and verified setups and a larger VOD review allowance.',
      '- Champion: everything in Elite, plus two live 1:1 coaching sessions with a Recon coach each month.',
      'Current prices are on the pricing page.',
      '## Where to see your plan',
      'Your Account page shows your plan and what you have access to. Your Recon home shows your membership status.',
      '## Why paid features can pause',
      'Paid features stay on while your membership is active. If a payment does not go through, paid features pause until the card is updated. If you paid and a feature is still locked, open a Get Help case: we can see your membership record, so you will not need to resend payment details.',
    ].join('\n'),
    status: 'draft',
    reviewedBy: null,
    sources: ['lambda/customer-success/domain/plans.mjs', 'lambda/subscription/index.mjs', 'src/pages/AccountPage.jsx', 'lambda/customer-success/domain/home.mjs'],
  },
  {
    slug: 'coaching-credits',
    title: 'Coaching credits and booking sessions',
    category: 'coaching_credits',
    intents: ['how_to', 'broken'],
    summary: 'How coaching credits are added, used and booked.',
    keywords: ['coaching', 'credits', 'session', 'book', 'booking', '1:1', 'one on one', 'reschedule', 'coach'],
    body: [
      '## How credits are added',
      'A Champion membership sets your coaching credits to two each time the monthly payment goes through. Unused credits do not roll over to the next month.',
      '## Booking',
      'Book from the coaching page. Sessions are 60 minutes, need at least 12 hours\' notice and can be booked up to 21 days ahead. A slot is held for a few minutes while you finish booking, and if you have a credit, the booking uses it.',
      '## Changing a session',
      'Cancelling a booked session does not put the credit back automatically. If you need to move a session, open a Get Help case first.',
      '## Credits look wrong?',
      'Open a Get Help case with roughly when you paid. We can see your bookings and the credits on record.',
    ].join('\n'),
    status: 'draft',
    reviewedBy: null,
    sources: ['lambda/booking/index.mjs', 'lambda/customer-success/domain/plans.mjs', 'public/coaching/index.html'],
  },
  {
    slug: 'billing-and-payments',
    title: 'Billing, payments and cancelling',
    category: 'billing_question',
    intents: ['how_to', 'broken'],
    summary: 'Update your card, see invoices or cancel through the billing portal, and what to do about a charge you do not recognise.',
    keywords: ['billing', 'payment', 'card', 'invoice', 'receipt', 'charged', 'charge', 'cancel', 'cancellation', 'refund', 'declined', 'past due', 'stripe'],
    body: [
      '## The billing portal',
      'Paid members open the billing portal from "Manage billing" on the Account page. Payments are handled by Stripe. In the portal you can update your card, see invoices and cancel.',
      '## If a payment fails',
      'Paid features pause until the card is updated. Update it in the billing portal. If you cannot find the way in, open a Get Help case.',
      '## A charge you do not recognise',
      'Open a Get Help case with the date and amount on your statement. We can see your membership record and will check it against the charge. Billing changes are reviewed and made by a person.',
    ].join('\n'),
    status: 'draft',
    reviewedBy: null,
    sources: ['lambda/subscription/index.mjs', 'src/pages/AccountPage.jsx', 'lambda/customer-success/domain/plans.mjs'],
  },
  {
    slug: 'get-better-vod-results',
    title: 'Get better results from AI VOD review',
    category: 'ai_result',
    intents: ['how_to', 'value'],
    summary: 'Small changes to what you upload make the review much sharper.',
    keywords: ['better results', 'vod tips', 'screenshots', 'context', 'map', 'site', 'operator', 'wrong map', 'generic', 'accuracy', 'improve'],
    body: [
      '## Pick the context',
      'Before uploading, open "Add context hints" and pick the map, site, side and operator. The review then uses that map and site\'s callouts and that operator\'s kit instead of guessing from the image.',
      '## Choose the right screenshots',
      '- Use screenshots from one round, in order: prep, the fight, and what happened after.',
      '- Full-screen, clear PNG or JPG images read best. Avoid phone photos of a monitor.',
      '- Make sure they are Rainbow Six Siege gameplay; other games are rejected.',
      '## Read it as a plan',
      'Where the review cannot tell something from the image, it says it is unsure. Take the practice plan into your next session and review again after a few matches.',
    ].join('\n'),
    status: 'draft',
    reviewedBy: null,
    sources: ['lambda/vod/index.mjs', 'lambda/vod/coach-contract.mjs', 'src/components/vod/SessionUploadZone.jsx'],
  },
  {
    slug: 'desktop-client',
    title: 'The desktop app',
    category: 'desktop_client',
    intents: ['how_to', 'broken'],
    summary: 'What we can and cannot see about the desktop app, and what to send us if it is not working.',
    keywords: ['desktop', 'app', 'desktop app', 'overlay', 'install', 'installer', 'download', 'capture card', 'live coach', 'windows'],
    body: [
      '## Availability',
      'The desktop app is not offered on the public site today. The Account page lists the desktop live coach as planned.',
      '## If you have the app and it is not working',
      'Recon cannot see which version you installed or whether it activated. Open a Get Help case with the app version, your Windows version, and whether you use PC capture or a console capture card.',
    ].join('\n'),
    status: 'draft',
    reviewedBy: null,
    sources: ['src/main.jsx', 'src/pages/AccountPage.jsx', 'config/product-truth.json', 'lambda/subscription/index.mjs'],
  },
  {
    slug: 'sign-in-and-password-help',
    title: 'Sign-in, confirmation code and password help',
    category: 'account_login',
    intents: ['how_to', 'broken'],
    summary: 'Fix the most common sign-in problems: missing confirmation code, forgotten password, email typed differently.',
    keywords: ['login', 'log in', 'sign in', 'password', 'forgot password', 'reset', 'confirmation code', 'verification', 'code', 'email', 'locked out'],
    body: [
      '## Confirmation code',
      'After sign-up, Recon emails a confirmation code. If it is not in your inbox, check spam and promotions. If you try to sign in before confirming, the sign-in page takes you back to the confirm step.',
      '## Forgot your password',
      'Choose "Forgot password" on the sign-in page. Recon emails a 6-digit code, and you enter it with your new password.',
      '## Email typed differently',
      'Recon signs you in with your email in lowercase. If your account was created with capital letters in the email, type it exactly as you signed up. If sign-in still fails, open a Get Help case from the email you signed up with.',
    ].join('\n'),
    status: 'draft',
    reviewedBy: null,
    sources: ['src/pages/AuthPage.jsx', 'src/hooks/useAuth.jsx'],
  },
])

export function articleBySlug(slug) {
  return ARTICLES.find((a) => a.slug === slug) || null
}
